### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by itspangler**
add waltham and needham in drop down

### CODE REVIEW

**Comment by garrettdashnelson** [comment]
@itspangler @emilyrbowe  I would like to wait to merge in any of the interactive help tour stuff until we have had a chance to consider this more fully, so can you either purge that from the `staging` branch, or else create a different branch with the `instance.json` commits and then PR from that different branch into `main`?

**Comment by itspangler** [comment]
sorry about that - @emilyrbowe would you mind moving the help button to a new branch, which will free up `staging` to be merged? i haven't touched that code so i just don't want to mess anything up when copying it over

**Comment by emilyrbowe** [comment]
Will do and will reply back once I've moved the changes to a new branch.

**Comment by emilyrbowe** [comment]
Moved the help button to its own branch — should be good to go now, @garrettdashnelson.

**Review by garrettdashnelson — APPROVED** [review]

**Pull request merged**
